### PR TITLE
Page the output

### PR DESCRIPTION
**Pull request by epitron**
Paging is nice!

### CODE REVIEW

**Comment by steakknife** [comment]
Thanks for the PR however this change seems fragile. The goals of this
project are to not break other plugins or bloat with random features which
belong elsewhere. I'm not certain it can be merged as-is and without
further testing but I just don't have the bandwidth right now.

**Comment by epitron** [comment]
Hmm? Why would this break other plugins?

As far as I can tell, the only think that might interfere with other plugins is overriding the print proc, which you've already done. Where's the harm in paging the output? Paging is alraedy the default behaviour in pry.

**Comment by epitron** [comment]
This might be a better way of imlpementing the pager: https://github.com/pry/pry/blob/master/lib/pry.rb#L19-L25

(That stagger_output snippet came from a 2012 wiki entry.)

**Comment by epitron** [comment]
Wait a minute... you're trolling me, aren't you. :)

**Comment by steakknife** [comment]
Don't whine, be a dick and make messes and not clean them up. Get lost.

**Comment by epitron** [comment]
Apologies for messing up your one line gem

**Pull request closed without merging**
